spring:
  application:
    name: api-gateway

  # API Gateway Configuration
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
           # - RedirectTo=302,https://youtube.com

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=x-customer-header,Saurav

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
